### ISSUE TITLE
Decrease CPU usage when scanning

### ISSUE THREAD

**Issue by colemancda** [PureSwift/GATT#18]
Use a different strategy that doesn't involve `sleep()` while scanning to improve energy efficiency and decrease unnecessary CPU usage. `DispatchSemaphore` might be a good solution.

**Comment by Ponyboy47** [comment]
I know that there is asyncAfter on DispatchQueues: https://developer.apple.com/documentation/dispatch/dispatchqueue/2300020-asyncafter

Could be handy if you can make the 2nd half of the scan function asynchronous

**Comment by colemancda** [comment]
The new Swift Concurrency integration fixes this.
