### ISSUE TITLE
Implementing a cross platform GATT Peripheral

### ISSUE THREAD

**Issue by sbrewin** [PureSwift/GATT#21]
Using PureSwift GATT I wish to  implement a GATT Peripheral that will be deployed on Darwin (MacOS, iOS, Mac Catalyst) and Linux platforms. How can a peripheral such as a Heart rate Monitor be implemented without custom coding for each platform?
Perhaps I am missing a trick?

**Comment by colemancda** [comment]
There are multiple projects using this library for that exact purpose. Please take a look at https://github.com/MillerTechnologyPeru/SmartLock
