### ISSUE TITLE
Documentation (for GATTPeripheral)

### ISSUE THREAD

**Issue by 0xPr0xy** [PureSwift/GATT#23]
Would it be possible to provide some documentation or examples of using `GATTPeripheral` to accomplish something like [this](https://github.com/RadiusNetworks/bluez/blob/master/test/example-gatt-server)?

Also any help would be appreciated, as my peripheral with service and characteristics isn't working for some reason even though nothing that can throw is throwing and it should be discoverable..

(I'm not an expert, but have a good understanding of bluetooth/GATT. I have setup a custom python GATT server that does similar things to the bluez example in the above link. I also have written the Central that talks to it in Swift on iOS - however porting the python code to pure swift so far is proving to be more difficult than anticipated.. )

Kind regards,

**Comment by fwcd** [comment]
Currently experimenting with this, might be related to #26.

**Comment by colemancda** [comment]
Take a look at https://github.com/MillerTechnologyPeru/SmartLock
