### ISSUE TITLE
Implement Bluetooth Explorer iOS app

### ISSUE THREAD

**Issue by colemancda** [PureSwift/GATT#6]
Implement an iOS app that duplicates the functionality of LightBlue Explorer using GATT.

**Comment by rvsrvs** [comment]
working on something similar for Linux.  Would do that first.  Is the idea to do it in this repo?

**Comment by colemancda** [comment]
A separate repo is fine too. The initial idea was to have it in the same repo for debugging.

**Comment by colemancda** [comment]
Implemented.
